version: '3.4'

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass s3nh@s3gur4!
    ports:
      - "6379:6379"

  investimentos.api:
    image: melviserpa/investimentos.api:develop
    build:
      context: .
      dockerfile: Investimentos.API/Dockerfile
    container_name: investimentos_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=America/Recife
    ports:
      - "5000:80"
